export default () => ({
  port: process.env.PORT || 3000,
  APP_URL: process.env.CLIENT_APP_URL || 'https://truffles.one',
  JWT_SECRET: process.env.JWT_SECRET || 'default_jwt_secret',
  EXP_TIME: parseInt(process.env.JWT_EXPIRATION_TIME) || 3600,
  REFRESH_EXP_TIME: parseInt(process.env.JWT_REFRESH_EXPIRATION_TIME) || 86400,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: parseInt(process.env.SMTP_PORT) || 587,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
  MONGODB_URI: process.env.MONGODB_URL,
  CONTRACT_ADDRESS: process.env.CONTRACT_ADDRESS,
  ADMIN_ADDRESS: process.env.ADMIN_ADDRESS,
  ADMIN_SEED_PHRASE: process.env.ADMIN_SEED_PHRASE,
  PINATA_URL: process.env.PINATA_URL || 'https://gateway.pinata.cloud/ipfs/',
  API_KEY: process.env.API_KEY,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  NODE_ENV: process.env.NODE_ENV || 'dev',
  NETWORK_NAME: process.env.NETWORK_NAME || 'mumbai',
  RPC_URL: process.env.RPC_URL,
  PINATA_API_KEY: process.env.PINATA_API_KEY,
  PINATA_API_SECRET: process.env.PINATA_API_SECRET,
});
